[package]
name = "gui_tool"
version = "1.0.0"
edition = "2024"

[dependencies]
iced = { version = "=0.14.0", default-features = false, features = [
    "tiny-skia",
    "tokio",
    "advanced",
] }
iced_aw = "0.14"
native-theme-iced = "0.5.6"
iced_aksel = "0.3.0"
iced_modifier = "0.5.1"
iced_plot = "0.4.0"
iced_toaster = "0.2.0"
iced_plus = "0.1.0"
iconflow = "1.0.0"
iced_navigation = { version = "1.6.0", features = ["drawer"] }
iced_split = "0.1.0"

serde_json = "1.0.145"
tokio = { version = "1.49.0", features = ["full"] }
rayon = "1.10"
pnet = "0.35.0"

anyhow = "1.0.100"
thiserror = "2.0.17"
log = "0.4.22"
tracing = "0.1.43"
futures = "0.3.31"
pnet_sys = "0.35.0"
async-trait = "^0.1"
glam = { version = "0.25.0", features = ["bytemuck"] }
bytemuck = { version = "1.0", features = ["derive"] }


[features]
default = ["net_scan", "net_capture", "json_fmt", "iced_aw"]

net_scan = []
net_capture = []
json_fmt = []
iced_aw = []
