appenders:
    stdout:
        kind: console
        encoder:
            pattern: "{d(%Y-%m-%d %H:%M:%S:%SSS)} [{pid}-{tid}-{thread}-{I}] {h({l})} {m} [{target}] [module:{M}|file:[{f}:{L}]]  {n}"
        filters:
            - kind: threshold
              level: info

root:
    level: info
    appenders:
        - stdout