refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h({l})} {m} [{pid}-{tid}-{T}-{I}] [{t}] [module:[{M}]-file:{f}:{L}] {n}"
    filters:
      - kind: threshold
        level: info
root:
  level: info
  appenders:
    - stdout
